### ISSUE TITLE
Lines ending with `;` returns `[]`

### ISSUE THREAD

**Issue by dvd101x** [josdejong/mathjs-codemirror#7]
Lines like

```jl
2+2;
```
return `[]`

I did try to fix it by using, but the lines are moving around.

`const answerNotEmpty = !(typeof answer === 'object' && answer.isResultSet && answer.entries.length === 0)`

**Comment by dvd101x** [comment]
Fixed by https://github.com/josdejong/mathjs-codemirror/commit/325bd885fb154b3cc94e38b19786a21eab2b21e5

**Comment by josdejong** [comment]
👍 thanks
