### ISSUE TITLE
not possible to declare functions

### ISSUE THREAD

**Issue by dvd101x** [josdejong/mathjs-codemirror#8]
Declaring

```julia
f(x) = x + 1 # yields f(x)
f(1) # yields TypeError: 'f' is not a function; its value is:
     # {"signatures": {"any": {}}, "_typedFunctionData": {"signatures": [{"params"...
```

I'm thinking of using a parser, but it might change a lot of the codebase.

**Comment by josdejong** [comment]
That is odd. When evaluating `const scope = new Map(); math.evaluate('f(x) = x + 1', scope)`, the defined function `f` is added to the `scope`, so it should be available in the next expression. I think it is some bug, this should "just" work with `scope`, no need to refactor to use `Parser`.

**Comment by dvd101x** [comment]
Oh that's right, no need to refactor to use a parser. It seems to be a definition of a typed function but I don't know where it comes from.

**Comment by dvd101x** [comment]
This was an issue caused by `math.clone`, it seems that cloning a function generates an object with the function's properties as a typed function (but not a function)

This might be an issue for mathjs for both functions and typed functions.
```js
const f = x=>x
console.log(typeof f)                       // yields function

const f_cloned = math.clone(f)
console.log(typeof f_cloned)                // yields object

const f_typed = math.typed({'number':f})
console.log(typeof f_typed)                 // yields function

const f_typed_cloned = math.clone(f_typed)
console.log(typeof f_typed_cloned)          // yields object
```

**Comment by josdejong** [comment]
That is a tricky one, good find! And thanks for fixing it.

I've created a bug fix for the `math.clone` function of mathjs, so that it throws an error in case of unsupported data types instead of treating it as an object, see https://github.com/josdejong/mathjs/commit/0222ff7aa9f85559a6f0a2daa6aa0c292849937a.
